version: '3.8'

services:
  flask-app:
    build: ./flask
    ports:
      - "80:5000"
      - "443:5000"  # We'll set up SSL later
    environment:
      - TELNYX_API_KEY=${TELNYX_API_KEY}
      - GOOGLE_SHEETS_CREDENTIALS=${GOOGLE_SHEETS_CREDENTIALS}
      - SPREADSHEET_ID=${SPREADSHEET_ID}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
